# Generated by Django 5.1.6 on 2025-02-17 12:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("city_id", models.CharField(max_length=10)),
                (
                    "last_updated",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
            options={
                "verbose_name_plural": "cities",
            },
        ),
        migrations.CreateModel(
            name="PrayerTime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("imsak", models.TimeField()),
                ("subuh", models.TimeField()),
                ("terbit", models.TimeField()),
                ("dhuha", models.TimeField()),
                ("dzuhur", models.TimeField()),
                ("ashar", models.TimeField()),
                ("maghrib", models.TimeField()),
                ("isya", models.TimeField()),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="prayer_times.city",
                    ),
                ),
            ],
            options={
                "unique_together": {("city", "date")},
            },
        ),
    ]
